version: "3.8"

services:
  postgresql:
        image: postgres:latest
        environment:
            - POSTGRES_USER=miraz
            - POSTGRES_PASSWORD=miraz
            - POSTGRES_DB=demo_dropbox
        ports: 
            - "5432:5432"
        restart: always
        volumes: 
          - postgres_data:/var/lib/postgresql/data
  # rabbitmq3:
  #   container_name: "rabbitmq-host"
  #   image: rabbitmq:3.8-management-alpine
  #   env_file:
  #     - .env
  #   ports:
  #       # AMQP protocol port
  #       - '5673:5672'
  #       # HTTP management UI
  #       - '15673:15672'
  app:
    container_name: "drop-box-integration"
    image: "docker-account-name/docker-project-nmae"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - drop-box-integration
    volumes:
      - ./src:/src
    ports:
      - 8010:8000



volumes:
  postgres_data: