"""user model update 

Revision ID: 7c8a61689db2
Revises: a59f3066d46d
Create Date: 2024-01-20 20:58:45.960382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8a61689db2'
down_revision: Union[str, None] = 'a59f3066d46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    op.drop_column('user', 'refesh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refesh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'refresh_token')
    # ### end Alembic commands ###
